// Code generated by mockery v2.50.4. DO NOT EDIT.

package tempmail

import mock "github.com/stretchr/testify/mock"

// mockReadCloser is an autogenerated mock type for the readCloser type
type mockReadCloser struct {
	mock.Mock
}

type mockReadCloser_Expecter struct {
	mock *mock.Mock
}

func (_m *mockReadCloser) EXPECT() *mockReadCloser_Expecter {
	return &mockReadCloser_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *mockReadCloser) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockReadCloser_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type mockReadCloser_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *mockReadCloser_Expecter) Close() *mockReadCloser_Close_Call {
	return &mockReadCloser_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *mockReadCloser_Close_Call) Run(run func()) *mockReadCloser_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockReadCloser_Close_Call) Return(_a0 error) *mockReadCloser_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockReadCloser_Close_Call) RunAndReturn(run func() error) *mockReadCloser_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: p
func (_m *mockReadCloser) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockReadCloser_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type mockReadCloser_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *mockReadCloser_Expecter) Read(p interface{}) *mockReadCloser_Read_Call {
	return &mockReadCloser_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *mockReadCloser_Read_Call) Run(run func(p []byte)) *mockReadCloser_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *mockReadCloser_Read_Call) Return(n int, err error) *mockReadCloser_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *mockReadCloser_Read_Call) RunAndReturn(run func([]byte) (int, error)) *mockReadCloser_Read_Call {
	_c.Call.Return(run)
	return _c
}

// newMockReadCloser creates a new instance of mockReadCloser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockReadCloser(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockReadCloser {
	mock := &mockReadCloser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
